name: Backend code formatting, linting and tests
on: push


jobs:
  server-code-check:
    name: Server code formatting and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'
      - name: Run gofmt
        run: test -z $(gofmt -l .)
        working-directory: meiki_server
      - name: Start test services
        run: docker-compose -f test_services.yml up -d
        working-directory: meiki_server
      - name: Wait for test services to be healthy
        timeout-minutes: 5
        run: |
          for cid in $(docker ps -a -q); do
            while [ "`docker inspect -f {{.State.Health.Status}} $cid`" != "healthy" ]; do
              sleep 2;
            done
          done
      - name: Run go test
        run: go test ./...
        working-directory: meiki_server
      - name: Stop test services
        run: docker-compose -f test_services.yml down
        working-directory: meiki_server

  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    needs: server-code-check
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
