name: Code formatting, linting and tests
on: push

jobs:
  server-code-check:
    name: Server code formatting and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5' 
      - name: Run gofmt
        run: test -z $(gofmt -l .)
        working-directory: meiki_server
      - name: Start test services
        run: docker-compose -f test_services.yml up -d
        working-directory: meiki_server
      - name: Wait for test services to be healthy
        timeout-minutes: 5
        run: |
          for cid in $(docker ps -a -q); do
            while [ "`docker inspect -f {{.State.Health.Status}} $cid`" != "healthy" ]; do 
              sleep 2; 
            done
          done
      - name: Run go test
        run: go test ./...
        working-directory: meiki_server
      - name: Stop test services
        run: docker-compose -f test_services.yml down
        working-directory: meiki_server
  ui-code-check:
    name: UI code formatting and linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set node version
        id: set_node_version
        run: echo "::set-output name=version::`cat .nvmrc`"
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.set_node_version.outputs.version }}
      - name: Install dependencies
        run: npm i
        working-directory: meiki_ui
      - name: Run svelte-check
        run: npm run check
        working-directory: meiki_ui
      - name: Run prettier
        run: npm run lint
        working-directory: meiki_ui
