name: Frontend code formatting, linting and tests
on: push

jobs:
  ui-code-check:
    name: UI code formatting and linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set node version
        id: set_node_version
        run: echo "::set-output name=version::`cat .nvmrc`"
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.set_node_version.outputs.version }}
      - name: Install dependencies
        run: npm i
        working-directory: meiki_ui
      - name: Run svelte-check
        run: npm run check
        working-directory: meiki_ui
      - name: Run prettier
        run: npm run lint
        working-directory: meiki_ui
  ui-cypress-tests:
    name: Run cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set node version
        id: set_node_version
        run: echo "::set-output name=version::`cat .nvmrc`"
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.set_node_version.outputs.version }}
      - name: Install dependencies
        working-directory: meiki_ui
        run: npm i
      - name: Wait for test services to be healthy
        timeout-minutes: 5
        run: |
          for cid in $(docker ps -a -q); do
            while [ "`docker inspect -f {{.State.Health.Status}} $cid`" != "healthy" ]; do 
              sleep 2; 
            done
          done
      - name: Start server
        working-directory: meiki_server
        run: |
          go run main.go </dev/null &>/dev/null &
          sleep 10
      - name: Start UI
        working-directory: meiki_ui
        run: |
          npm run dev </dev/null &>/dev/null &
          sleep 5 
      - name: Run cypress
        working-directory: meiki_ui
        run: npx cypress run
