name: Frontend code formatting, linting
on: push

jobs:
  ui-code-check:
    name: UI code formatting and linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set node version
        id: set_node_version
        run: echo "::set-output name=version::`cat .nvmrc`"
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.set_node_version.outputs.version }}
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i
        working-directory: meiki_ui
      - name: Build UI
        run: pnpm run build
        working-directory: meiki_ui
      - name: Run svelte-check
        run: pnpm run check
        working-directory: meiki_ui
      - name: Run prettier
        run: pnpm run lint
        working-directory: meiki_ui
