name: Frontend tests
on: push

jobs:
  ui-cypress-tests:
    name: Run cypress tests
    runs-on: ubuntu-latest
    env:
      SERVER_URL: "localhost:8080"
      FRONTEND_URL: "localhost:3000"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set node version
        id: set_node_version
        run: echo "::set-output name=version::`cat .nvmrc`"
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.set_node_version.outputs.version }}
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'
      - name: Install dependencies
        working-directory: meiki_ui
        run: npm i
      - name: Install dependencies for server
        working-directory: meiki_server
        run: go get
      - name: Start test services
        run: docker-compose -f test_services.yml up -d
        working-directory: meiki_server
      - name: Wait for test services to be healthy
        timeout-minutes: 5
        run: |
          for cid in $(docker ps -a -q); do
            while [ "`docker inspect -f {{.State.Health.Status}} $cid`" != "healthy" ]; do
              sleep 2;
            done
          done
      - name: Start server
        working-directory: meiki_server
        timeout-minutes: 1
        run: |
          go run main.go > server-logs.txt &
          while [ "`curl --silent $SERVER_URL/health/`" != '"Healthy"' ]; do
            sleep 1;
          done
      - name: Start UI
        working-directory: meiki_ui
        run: |
          npm run dev &
          while [[ ! "`curl --silent -I $FRONTEND_URL/ | grep 200`" =~ "200" ]]; do
            sleep 1;
          done
      - name: Run cypress
        working-directory: meiki_ui
        run: npx cypress run
      - name: Upload Test artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: server-logs
          path: meiki_server/server-logs.txt
      - name: Upload Failed Test screenshots if any
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: meiki_ui/cypress/screenshots/
